# See https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
name: 'Upload Artifacts'
description: 'Upload artifacts'
inputs:
  event_name:
    description: 'The name of the event'
    type: string
    required: true
  head_sha:
    description: 'The sha code of the head commit'
    type: string
    required: true
  sender_repo_owner:
    description: 'The name of the repository owner'
    type: string
    required: true
  sender_repo_ref:
    description: 'The name of the branch / ref'
    type: string
    required: true
  sender_repo_name:
    description: 'The name of the repository only (without owner)'
    type: string
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
