FROM ubuntu:20.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3.6 \
    python3-pip \
    python3.6-dev

RUN pip3 install --upgrade pip

EXPOSE 80

#------ OnionNet specific installation ------#
RUN apt-get install git wget bzip2
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH="/opt/conda/bin:${PATH}"

#RUN pip3 install tensorflow
RUN git lfs clone https://github.com/zhenglz/onionnet.git
RUN cd onionnet

RUN conda create -n onionnet python=3.6
RUN conda activate onionnet

RUN conda install -c anaconda scipy numpy pandas
RUN conda install tensorflow
RUN conda install -c omnia mdtraj
RUN conda install -c openbabel openbabel

#------ Test installation ------#
RUN python generate_features.py -h
RUN python predict.py -h

RUN conda env create -f onet_env.yaml
RUN conda activate onionnet

#------ Run examples ------#